### ISSUE TITLE
Cart Assembler poor performance when idle.

### ISSUE THREAD

**Issue by ProsperCraft** [modmuss50/SC2#128]
When the Cart Assembler is sitting idle doing nothing, it's taking up server ticks.

![2018-02-25_19 36 53](https://user-images.githubusercontent.com/4427684/36651025-dff84b92-1a63-11e8-8857-13ac31d13f82.png)
![2018-02-25_19 36 55](https://user-images.githubusercontent.com/4427684/36651027-e1f34b86-1a63-11e8-9bc9-2c292e5e3dea.png)

StevesCarts-1.12.2-2.4.17.88

**Comment by GoryMoon** [comment]
I can't get that amount of tick usage but I've identified a part that takes some time.
It checks if it can refill fuel every tick and the culprit is it calls some vanilla code to get the fuel level, I've changed this to only check if some fuel have been used and a slower check cycle, if it can fill it will go faster until it can't fill anymore.
Related commit: 93844e6

**Comment by ProsperCraft** [comment]
Thank you.
