### ISSUE TITLE
Wheel recipe conflict

### ISSUE THREAD

**Issue by LemADEC** [modmuss50/SC2#173]
As of 1.12.2-2.4.27.127, the wooden wheel recipe is conflicting with other mod's wooden gear recipes.
Consider using a different shape (sticks in corner or inverse stick and plank) to avoid such recurrent recipe conflict.

**Comment by GoryMoon** [comment]
It's not like it was changed to the current recipe recently, the current recipe for the wooden wheel has been the same since mid-2012 when SC2 was first created, so it's been around for a while.

I don't see a real need to change it (part to keep it consistent to the other wheel recipes), just going to add an alternative to it.

**Comment by LemADEC** [comment]
Yes, that recipe is a pain since the beginning; fixing it in the mod itself saves us from fixing it in so many modpacks.
For the record, it currently overwrite/takes priority over the wooden gear, that's why I was proposing to change it since adding an alternative won't fix the overwrite.
